services:
  dvwa:
    image: vulnerables/web-dvwa:latest
    container_name: sentra-lab-dvwa
    ports:
      - "8081:80"
    restart: unless-stopped
    networks:
      - sentra_net

  juice-shop:
    image: bkimminich/juice-shop:latest
    container_name: sentra-lab-juice-shop
    ports:
      - "3001:3000"
    restart: unless-stopped
    networks:
      - sentra_net
