import os
import textwrap
from datetime import datetime

from fpdf import FPDF
from fpdf.enums import XPos, YPos


def sanitize_text(text: str) -> str:
    """Remove non-Latin1 characters that FPDF can't handle."""
    if not text:
        return ""
    replacements = {
        '•': '-', '–': '-', '—': '-',
        '\u201c': '"', '\u201d': '"', '\u2018': "'", '\u2019': "'",
        '⛔': '[X]', '✔': '[OK]', '✓': '[OK]', '❌': '[X]',
        '🎯': '*', '🛡️': '*', '⚡': '*', '★': '*',
        '→': '->', '←': '<-', '≥': '>=', '≤': '<=',
    }
    for u, a in replacements.items():
        text = text.replace(u, a)
    text = text.replace("**", "").replace("__", "").replace("##", "").replace("# ", "")
    return text.encode('latin-1', 'ignore').decode('latin-1')


def wrap_text(text: str, w: int = 85) -> str:
    """Break all lines to a max width to prevent fpdf2 overflow."""
    out = []
    for line in text.split('\n'):
        out.append(textwrap.fill(line, width=w) if len(line) > w else line)
    return '\n'.join(out)


class AuditReport(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 16)
        self.cell(0, 10, 'Sentra.AI - Security Audit Report', new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.set_draw_color(52, 152, 219)
        self.set_line_width(0.5)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(8)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Sentra.AI')

    def section_title(self, title):
        self.set_font('Helvetica', 'B', 13)
        self.set_text_color(44, 62, 80)
        self.cell(0, 10, sanitize_text(title), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.set_text_color(0, 0, 0)
        self.ln(2)

    def body_text(self, text):
        self.set_font('Helvetica', '', 10)
        self.multi_cell(0, 5, sanitize_text(wrap_text(text)))
        self.ln(4)

    def mono_block(self, text, limit=5000):
        self.set_font('Courier', '', 8)
        self.multi_cell(0, 4, sanitize_text(wrap_text(text[:limit], w=75)))
        self.ln(4)


def generate_pdf_report(scan_data: dict, filename: str = "report.pdf") -> str:
    pdf = AuditReport()
    pdf.add_page()

    target = sanitize_text(scan_data.get('target', 'Unknown'))
    scan_id = sanitize_text(str(scan_data.get('scan_id', 'N/A')))

    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 8, f"Target: {target}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.cell(0, 8, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.cell(0, 8, f"Scan ID: {scan_id}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    risk_score = scan_data.get("risk_score")
    risk_label = scan_data.get("risk_label")
    if risk_score is not None:
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(0, 8, f"Risk Score: {risk_score}/10 - {risk_label}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(8)

    # --- AI Analysis ---
    pdf.section_title("Executive Summary (AI Analysis)")
    pdf.body_text(scan_data.get("analysis", "No analysis available."))

    # --- Nmap ---
    pdf.add_page()
    pdf.section_title("Technical Details (Nmap)")
    pdf.mono_block(scan_data.get("nmap", "No Nmap data."))

    # --- Nikto ---
    nikto = scan_data.get("nikto", "")
    if nikto and len(nikto.strip()) > 10:
        pdf.add_page()
        pdf.section_title("Web Vulnerabilities (Nikto)")
        pdf.mono_block(nikto)

    # --- Fixes ---
    fixes_data = scan_data.get("fixes", {})
    if fixes_data and fixes_data.get("findings"):
        pdf.add_page()
        os_detected = fixes_data.get('os_detected', 'unknown').upper()
        pdf.section_title(f"Remediation Playbooks (OS: {os_detected})")

        for i, finding in enumerate(fixes_data["findings"], 1):
            pdf.set_font("Helvetica", "B", 10)
            severity = sanitize_text(finding.get("severity", "UNKNOWN"))
            desc = sanitize_text(finding.get("description", ""))
            if len(desc) > 75:
                desc = desc[:72] + "..."
            pdf.cell(0, 7, f"Fix #{i} [{severity}]: {desc}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

            pdf.set_font("Helvetica", "I", 8)
            if "port" in finding:
                pdf.cell(0, 5, f"Source: Nmap - Port {finding['port']}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            else:
                src = sanitize_text(finding.get('finding', 'Web vulnerability'))
                if len(src) > 55:
                    src = src[:52] + "..."
                pdf.cell(0, 5, f"Source: Nikto - {src}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

            cmds = finding.get("commands", [])
            if cmds:
                pdf.set_font("Courier", "", 8)
                for cmd in cmds:
                    if cmd.strip():
                        pdf.set_x(pdf.l_margin)
                        pdf.multi_cell(0, 4, sanitize_text(wrap_text(cmd, w=75)))
            pdf.ln(4)

        ai_recs = fixes_data.get("ai_recommendations", "")
        if ai_recs:
            pdf.ln(4)
            pdf.section_title("Strategic AI Recommendations")
            pdf.body_text(ai_recs[:3000])

    report_path = os.path.join(os.getcwd(), filename)
    pdf.output(report_path)
    return report_path
